services:
  mysql:
    image: mysql:8.0
    container_name: bookgather-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - bookgather-mysql-data:/var/lib/mysql

volumes:
  bookgather-mysql-data:
