apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: bookgather/review-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql-bookgather
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: reviewdb
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  selector:
    app: review-service
  ports:
    - port: 8080
      targetPort: 8080
